name: mobileSecretCodes
description: A mobile application to provide all the hidden and secret codes for all android and specific mobile devices.
publish_to: 'none'
version: 25.10.31+9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.2.1
  flutter_custom_clippers: ^2.1.0

  # Permissions & Utilities
  permission_handler: ^12.0.1
  url_launcher: ^6.2.5
  share_plus: ^7.2.1
  in_app_review: ^2.0.8

  # Networking & Data
  http: ^1.2.0
  html: ^0.15.4

  # Monetization
  google_mobile_ads: ^5.0.0

  # PDF Viewer
  syncfusion_flutter_pdfviewer: ^27.1.48

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 24
